Repository eoeo-org/pow, pull requests merged in 2023-08, with the labels that each got.

#673 fix(deps): remove dependency @discordjs/rest
  package.json
  pnpm-lock.yaml
Labels: dependencies, semver:patch

#674 fix(docker): remove pnpm patch
  Dockerfile
Labels: semver:patch

#675 chore(actions): Fix maintain-quality.yml
  .github/workflows/maintain-quality.yml
Labels: semver:none

#678 ci: Update maintain-quality.yml
  .github/workflows/maintain-quality.yml
Labels: semver:none

#686 chore: update renovate config
  .github/renovate.json
Labels: semver:none

#689 chore(renovate): Disable dependencyDashboardOSVVulnerabilitySummary
  .github/renovate.json
Labels: semver:none

#691 chore: Add "tsc: build - tsconfig.json" task
  .vscode/tasks.json
Labels: semver:none

#692 feat(commands)!: `/user-settings` に移行しUXを向上
  README.md
  package.json
  pnpm-lock.yaml
  src/commands/random.ts
  src/commands/userSettings.ts
  src/commands/view.ts
  src/commands/voice.ts
Labels: semver:major

#697 fix: refactor
  package.json
  pnpm-lock.yaml
  src/connectionCtx.ts
  src/utils.ts
  src/voiceRead.ts
Labels: semver:patch

#699 feat(commands)!: `/readtoggle` を `/ttsmute` に置き換え
  README.md
  src/commands/readtoggle.ts
  src/commands/ttsmute.ts
  src/connectionCtx.ts
  src/events/messageCreate.ts
Labels: semver:major

#703 refactor: 読み上げ関連処理に型を追加
  src/connectionCtx.ts
  src/utils.ts
  src/voiceRead.ts
Labels: semver:none

#708 chore: Hello SWC
  .github/workflows/maintain-quality.yml
  .swcrc
  .vscode/launch.json
  .vscode/tasks.json
  Dockerfile
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: semver:none

#709 chore(Docker): fix regex for pnpm
  Dockerfile
Labels: semver:none

#710 fix(commands): help の返答メッセージを修正
  src/commands/help.ts
Labels: semver:patch

#715 feat(command): Add /rejoin command.
  src/commands/rejoin.ts
Labels: semver:minor

#717 refactor: typings 要らん
  src/index.ts
Labels: semver:none

#718 refactor: integrity 要らんくなったっぽい
  src/index.ts
Labels: semver:none

#719 refactor: integrity 要らんくなったっぽい2
  src/commands/help.ts
Labels: semver:none

#720 refactor(commands): メッセージの書き方を変更
  src/commands/join.ts
  src/commands/leave.ts
  src/commands/purge.ts
  src/commands/rejoin.ts
  src/commands/skip.ts
  src/commands/userSettings.ts
Labels: semver:none

#721 chore(scripts): Windows でも dev が動くように修正
  package.json
Labels: semver:none

#722 fix(commands): add command validations
  src/commands/userSettings.ts
Labels: semver:patch

#724 chore(githooks): install に失敗しても restore しないようにする
  .husky/post-index-change
Labels: semver:none

#725 refactor: 要らんコード
  src/voiceRead.ts
Labels: semver:none

#726 refactor: events を Sapphire 管理下に移動
  src/events/channelUpdate.ts
  src/events/guildMemberAdd.ts
  src/events/guildMemberRemove.ts
  src/events/index.ts
  src/events/messageCreate.ts
  src/events/voiceStateUpdate.ts
  src/index.ts
  src/listeners/channelUpdate.ts
  src/listeners/guildMemberAdd.ts
  src/listeners/guildMemberRemove.ts
  src/listeners/messageCreate.ts
  src/listeners/voiceStateUpdate.ts
Labels: semver:none

#728 fix(commands): rejoin コマンドを修正
  src/commands/rejoin.ts
Labels: semver:patch

#730 chore(container): curl に `--compressed`オプションを追加
  Dockerfile
Labels: semver:none

#731 fix(commands): Fix error message
  src/commands/join.ts
Labels: semver:patch

#735 refactor: worker 機能をリファクタリング
  src/index.ts
  src/worker.ts
Labels: semver:none

#736 refactor: worker 機能をリファクタリング2
  src/worker.ts
Labels: semver:none

#739 fix(refactor): エラー処理を修正
  src/commands/join.ts
  src/commands/leave.ts
  src/commands/purge.ts
  src/commands/read.ts
  src/commands/rejoin.ts
  src/commands/reset.ts
  src/commands/skip.ts
  src/commands/ttsmute.ts
  src/components/preCheck.ts
  src/connectionCtx.ts
  src/errors/ConnectionError.ts
  src/errors/FetchResponseError.ts
  src/errors/HandleInteractionError.ts
  src/errors/PowError.ts
  src/errors/WorkerError.ts
  src/errors/index.ts
  src/guildCtx.ts
  src/voiceRead.ts
Labels: semver:patch

#742 refactor: use hard private
  src/connectionCtx.ts
  src/worker.ts
Labels: semver:none

#743 fix: add handle db errors
  src/commands/userSettings.ts
  src/connectionCtx.ts
  src/db.ts
  src/errors/DBError.ts
  src/errors/index.ts
Labels: semver:patch

#744 Revert "chore(deps): update dependency @swc/core to v1.3.81"
  package.json
  pnpm-lock.yaml
Labels: semver:none

#748 refactor: use package.json without assert
  .swcrc
  src/commands/help.ts
  src/index.ts
Labels: semver:none
