Repository eoeo-org/pow, pull requests merged in 2023-05, with the labels that each got.

#488 fix: .env-example
  .env-example
Labels: semver:none

#489 fix: worker check
  src/commands/join.ts
Labels: semver:patch

#492 fix: worker check
  src/commands/join.ts
Labels: semver:patch

#498 Revert "Release v2.1.8"
  package.json
Labels: release

#500 Await destroy
  package.json
  patches/discord.js@14.11.0.patch
  pnpm-lock.yaml
  src/index.ts
Labels: semver:patch

#501 Add restart message
  src/index.ts
Labels: semver:minor

#502 Fix restart message color
  src/index.ts
Labels: semver:patch

#503 Fix Dockerfile
  Dockerfile
Labels: semver:none

#506 Refactor join command
  src/commands/join.ts
Labels: semver:patch

#508 Fix docker action
  .github/workflows/docker.yml
Labels: semver:none

#513 Fix help message
  src/commands/help.ts
Labels: semver:patch

#517 Add reset command
  src/commands/reset.ts
Labels: semver:minor

#526 Refactor: contentConverter
  src/contentConverter.ts
Labels: semver:patch

#529 Fix join command
  src/commands/join.ts
Labels: semver:patch

#531 Fix join
  src/guildCtx.ts
Labels: semver:patch

#534 Add skip command
  src/commands/skip.ts
Labels: semver:minor

#533 Fix sort
  src/guildCtx.ts
Labels: semver:patch

#536 Update semver-label-check.yml
  .github/workflows/semver-label-check.yml
Labels: semver:none

#538 Fix versioning action
  .github/workflows/versioning.yml
  .github/workflows/versioning/main.sh
Labels: semver:none

#539 Revert "Fix versioning action"
  .github/workflows/versioning.yml
  .github/workflows/versioning/main.sh
Labels: semver:none

#541 Fix versioning action
  .github/workflows/versioning.yml
  .github/workflows/versioning/main.sh
Labels: semver:none

#542 十分な量のBotがいる場合、VCとBotが一対一対応するように変更
  src/guildCtx.ts
Labels: semver:minor

#544 可能な場合、別のVCで使われているBotを入れ替えてでも同じBotを使うように修正
  src/connectionCtx.ts
  src/guildCtx.ts
  src/index.ts
Labels: semver:patch

#553 Remove pnpm store from Docker image
  Dockerfile
Labels: semver:none

#554 Update README
  README.md
Labels: semver:none
