Repository eoeo-org/pow, pull requests merged in 2023-10, with the labels that each got.

#821 refactor: refactor error
  src/connectionCtx.ts
  src/errors/FetchResponseError.ts
  src/errors/PowError.ts
  src/utils.ts
Labels: semver:none

#833 fix: エラーの握りつぶしをやめる
  src/connectionCtx.ts
Labels: semver:patch

#837 chore: tsconfig を修整
  .gitignore
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: semver:none

#838 feat: 「プレイ中」表記がない presence にする
  src/events/ready.ts
  src/worker.ts
Labels: semver:minor

#851 chore(deps): update Node.js to v21.0.0
  .npmrc
Labels: semver:none

#860 chore: add setting examples to README.md
  README.md
Labels: semver:none

#864 Revert "chore: Dockerfile 改善"
  Dockerfile
Labels: semver:none

#865 chore: Dockerfile 改善
  Dockerfile
Labels: semver:none

#867 refactor(deps): remove unused dependencies
  package.json
  pnpm-lock.yaml
Labels: semver:none

#868 perf(deps): change to sodium-native
  package.json
  pnpm-lock.yaml
Labels: semver:patch

#869 chore: Dockerfile 改善
  Dockerfile
Labels: semver:none
