Repository eoeo-org/pow, pull requests merged in 2023-07, with the labels that each got.

#618 Add worker's Add to Server URL
  README.md
Labels: semver:none

#620 add support stage channel
  src/commands/join.ts
  src/commands/leave.ts
  src/connectionCtx.ts
  src/guildCtx.ts
  src/index.ts
  src/joinMessage.ts
Labels: semver:minor

#622 remove unnecessary await
  src/commands/leave.ts
  src/commands/reset.ts
  src/guildCtx.ts
  src/index.ts
Labels: semver:patch

#624 refactor(event)
  src/events/guildMemberAdd.ts
  src/events/guildMemberRemove.ts
  src/events/index.ts
  src/events/messageCreate.ts
  src/events/ready.ts
  src/events/voiceStateUpdate.ts
  src/index.ts
Labels: semver:patch

#625 add error handler
  src/events/voiceStateUpdate.ts
Labels: semver:patch

#627 add support RequestToSpeak
  src/events/channelUpdate.ts
  src/events/index.ts
  src/events/voiceStateUpdate.ts
  src/index.ts
Labels: semver:minor

#629 remove export from client
  src/commands/read.ts
  src/guildCtx.ts
  src/index.ts
  src/joinMessage.ts
Labels: semver:patch

#633 Remove StageChannel check in voice channel logic
  src/commands/purge.ts
  src/commands/read.ts
  src/commands/skip.ts
Labels: semver:patch

#640 fix(worker): workerの準備が整う前にjoinできるのが修正できたかもしれない
  src/commands/join.ts
  src/index.ts
  src/joinMessage.ts
  src/worker.ts
Labels: semver:patch

#642 fix docker action
  .github/workflows/docker.yml
Labels: semver:none

#644 fix: 意味わからんことしてるのを直した
  src/contentConverter.ts
Labels: semver:patch

#650 fix: url convert
  src/contentConverter.ts
Labels: semver:patch

#656 feat: add read stickers feature
  src/commands/read.ts
  src/contentConverter.ts
  src/events/messageCreate.ts
Labels: semver:minor

#664 chore: Update maintain-quality.yml
  .github/workflows/maintain-quality.yml
Labels: semver:none

#666 fix dev script
  package.json
Labels: semver:none
