Repository eoeo-org/pow, pull requests merged in 2023-04, with the labels that each got.

#402 Add versioning action
  .github/workflows/versioning.yml
  .github/workflows/versioning/main.sh
Labels: semver:none

#404 Hello TypeScript
  .gitignore
  Dockerfile
  package.json
  pnpm-lock.yaml
  src/commands/join.ts
  src/commands/leave.js
  src/commands/leave.ts
  src/commands/purge.js
  src/commands/purge.ts
  src/commands/random.js
  src/commands/random.ts
  src/commands/read.js
  src/commands/read.ts
  src/commands/readtoggle.js
  src/commands/readtoggle.ts
  src/commands/view.js
  src/commands/view.ts
  src/commands/voice.ts
  src/contentConverter.ts
  src/deployGlobalCommand.js
  src/deployGuildCommand.js
  src/env.d.ts
  src/index.ts
  src/utils.ts
  src/voiceRead.ts
  tsconfig.json
Labels: semver:patch

#407 Upgrade Node.js to 18.16.0
  .npmrc
Labels: semver:none

#408 Fix leave command
  src/commands/leave.ts
Labels: semver:patch

#412 Add version info
  package.json
  src/index.ts
Labels: semver:minor

#418 Fix to catch 50013 error
  src/voiceRead.ts
Labels: semver:patch

#420 Fix to catch 50013 error (2)
  src/voiceRead.ts
Labels: semver:patch

#422 Add docker publish action
  .github/workflows/docker.yml
Labels: semver:none

#426 Fix platforms
  .github/workflows/docker.yml
Labels: semver:none

#427 Fix platforms (2)
  .github/workflows/docker.yml
Labels: semver:none

#421 Fix emoji convert
  src/contentConverter.ts
Labels: semver:patch

#432 Fix voice command
  src/commands/voice.ts
Labels: semver:patch

#434 Add diff
  src/commands/voice.ts
Labels: semver:minor

#436 Add SemVer label check action
  .github/workflows/semver-label-check.yml
Labels: semver:none

#437 Update docker publish action
  .github/workflows/docker.yml
Labels: semver:none

#438 Update docker publish action
  .github/workflows/docker.yml
Labels: semver:none

#440 型設定
  package.json
  pnpm-lock.yaml
  src/index.ts
  src/voiceRead.ts
Labels: semver:none

#443 feat: process.title を書き換える
  src/index.ts
Labels: semver:minor

#442 Add launch.json for VSCode
  .vscode/launch.json
Labels: semver:none

#445 Update readme
  README.md
Labels: semver:none

#446 Fix diff appearance
  src/commands/voice.ts
Labels: semver:patch

#449 Fix signal handle
  src/index.ts
Labels: semver:patch

#451 Refactor voiceRead
  src/commands/readtoggle.ts
  src/commands/view.ts
  src/commands/voice.ts
  src/db.ts
  src/guildCtx.ts
  src/index.ts
  src/voiceRead.ts
Labels: semver:none

#452 Fix emoji convert (2)
  src/contentConverter.ts
Labels: semver:patch

#456 Refactor commands
  src/commands/leave.ts
  src/commands/purge.ts
  src/commands/random.ts
  src/commands/read.ts
  src/commands/readtoggle.ts
  src/commands/view.ts
  src/commands/voice.ts
Labels: semver:none

#457 Add help command
  README.md
  src/commands/help.ts
  src/index.ts
Labels: semver:minor

#459 Fix random command
  src/commands/random.ts
  src/commands/voice.ts
  src/db.ts
  src/utils.ts
  src/voiceRead.ts
Labels: semver:patch

#461 要らん
  package.json
  src/index.ts
Labels: semver:none

#470 Fix: ワーカーも落ちるように修正
  src/index.ts
Labels: semver:patch

#472 feat: workerのstatusをdndにしてわかりやすくする
  src/worker.ts
Labels: semver:minor

#474 Fix: joinコマンドを修正
  src/commands/join.ts
Labels: semver:patch

#477 メンションコマンド時にはスラッシュコマンドへ誘導するように変更
  src/commands/help.ts
Labels: semver:patch

#479 Fix: workerが起動し終わる前にjoinすると壊れるのを修正
  src/commands/join.ts
Labels: semver:patch
