Repository eoeo-org/pow, pull requests merged in 2024-01, with the labels that each got.

#948 ci: specify buildx version
  .github/renovate.json
  .github/workflows/docker.yml
Labels: semver:none

#973 ci: update release workflow
  .github/files/release-please/.release-please-manifest.json
  .github/files/release-please/release-please-config.json
  .github/workflows/release-please.yml
Labels: semver:none

#972 feat: URL の正規表現を変更してあらゆる URL に対応する
  src/contentConverter.ts
Labels: semver:minor

#974 ci: 二重にビルドを実行しないようにする
  .github/workflows/docker.yml
Labels: semver:none

#976 chore: Update codeowners
  .github/CODEOWNERS
Labels: semver:none

#975 fix: handle case where no reply message exists
  src/connectionCtx.ts
Labels: semver:patch

#978 fix: Fix CODEOWNERS
  .github/CODEOWNERS
Labels: semver:patch

#979 chore: disable auto merge
  .github/renovate.json
Labels: semver:none

#980 ci: add cleanup-caches workflow
  .github/workflows/cleanup-caches.yml
Labels: semver:none

#986 chore: Update renovate.json
  .github/renovate.json
Labels: semver:none

#987 ci: always docker build check
  .github/workflows/docker.yml
Labels: semver:none

#992 ci: fix semver label workflow
  .github/workflows/semver-label.yml
Labels: semver:none
