Repository eoeo-org/pow, pull requests merged in 2024-07, with the labels that each got.

#1332 ci: update trigger_renovate.yml
  .github/workflows/trigger_renovate.yml
Labels: semver:none

#1333 ci: update release bot name
  .github/workflows/docker.yml
Labels: semver:none

#1347 chore: remove hack for npm
  .npmrc
  package.json
Labels: semver:none

#1348 ci: update org name
  .github/workflows/release-please.yml
Labels: semver:none

#1363 fix: runs even if WORKER_TOKENS is empty
  src/worker.ts
Labels: semver:patch

#1364 build: fix FromAsCasing
  Dockerfile
Labels: semver:none

#1369 chore: update ESLint config property name
  .vscode/settings.json
Labels: semver:none

#1384 chore: update @tsconfig/node21 to node22
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: semver:none

#1385 deps: change prisma to devDependencies
  package.json
  pnpm-lock.yaml
Labels: semver:patch

#1387 chore: add Prisma.prisma to recommendations extensions
  .vscode/extensions.json
Labels: semver:none

#1388 build: fix Dockerfile for prisma
  Dockerfile
  prisma/schema.prisma
Labels: semver:none

#1390 build: add migrate image
  .github/workflows/docker.yml
  compose.yaml
  migrate.Dockerfile
Labels: semver:none

#1391 build: remove unnecessary package.json
  Dockerfile
Labels: semver:none

#984 feat: prevent timeout in command response
  src/commands/join.ts
  src/commands/leave.ts
  src/commands/read.ts
  src/commands/rejoin.ts
  src/commands/reset.ts
  src/commands/userSettings.ts
  src/connectionCtx.ts
  src/guildCtx.ts
  src/utils.ts
Labels: semver:minor
