Repository eoeo-org/pow, pull requests merged in 2024-05, with the labels that each got.

#1224 ci: migrate release-please-action
  .github/workflows/release-please.yml
Labels: semver:none

#1239 ci: fix docker workflow
  .github/workflows/docker.yml
Labels: semver:none

#1240 feat: add parseTimestamp
  src/contentConverter.ts
Labels: semver:minor

#1244 fix: update dateStyle to 'long' in contentConverter.ts
  src/contentConverter.ts
Labels: semver:patch

#1247 feat: Add relativetime for timestamp
  src/contentConverter.ts
Labels: semver:none

#1253 docs: Update install links
  README.md
Labels: semver:none
